# Generated by Django 5.0.3 on 2024-03-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkobject',
            name='hierarchy',
            field=models.CharField(max_length=1, verbose_name='уровень иерархии'),
        ),
        migrations.AlterField(
            model_name='networkobject',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='network.product'),
        ),
    ]
