# Generated by Django 5.0.3 on 2024-03-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_alter_networkobject_hierarchy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkobject',
            name='hierarchy',
            field=models.IntegerField(verbose_name='уровень иерархии'),
        ),
    ]
