# Generated by Django 5.0.3 on 2024-03-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_networkobject_hierarchy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkobject',
            name='hierarchy',
            field=models.IntegerField(default=0, verbose_name='уровень иерархии'),
        ),
        migrations.AlterField(
            model_name='networkobject',
            name='products',
            field=models.ManyToManyField(to='network.product'),
        ),
    ]
