# Generated by Django 5.0.3 on 2024-03-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_networkobject_hierarchy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkobject',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='network.product'),
        ),
    ]
