# Generated by Django 5.0.3 on 2024-03-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_alter_networkobject_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkobject',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ManyToManyField(to='network.networkobject'),
        ),
    ]
